---
micronaut:
    application:
        name: gateway
    caches.discovery-client.enabled: false
---
#tracing:
#  zipkin:
#    enabled: true
#    http:
#      url: http://localhost:9411
#    sampler:
#      probability: 0.1
---
---
consul:
  client:
    registration:
      enabled: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
